---
- name: Assemble Consul & Nomad cluster (bos)
  hosts: bos
  become: true
  any_errors_fatal: true
  roles:
    - ansible-consul
    - ansible-nomad
  vars: 
    consul_iface: wg0
    consul_dnsmasq_local_service: true
    consul_group_name: bos
    nomad_iface: wg0
    nomad_group_name: bos
    nomad_podman_enable: true
    nomad_network_interface: wg0
    nomad_cni_enable: true
    nomad_host_networks:
    - name: public
      interface: eth0
      reserved_ports: 22
    consul_connect_enabled: true
    consul_dnsmasq_enable: true


